# Generated by Django 5.2.4 on 2025-07-31 06:36

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0001_initial'),
    ]

    operations = [
            migrations.AddField(
                model_name='user',
                name='logo',
                field=models.CharField(max_length=800, null=True, blank=True),
            ),
            migrations.AddField(
                model_name='user',
                name='gst_certificate',
                field=models.CharField(max_length=800, null=True, blank=True),
            ),
            migrations.AddField(
                model_name='user',
                name='pan_card',
                field=models.CharField(max_length=800, null=True, blank=True),
            ),
        ]