# Generated by Django 5.2.4 on 2025-08-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0002_add_company_docs_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gst_certificate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pan_card',
        ),
    ]
